version: '2'
services:
    school-app:
        image: school
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://school-postgresql:5432/school
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    school-postgresql:
        extends:
            file: postgresql.yml
            service: school-postgresql
